version: "2.2"

services:
    proxy:
        image: nginx:alpine
        container_name: proxy
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf.d/:/etc/nginx/conf.d

    server:
        build: ./server
        container_name: server
        hostname: server
        volumes:
            - ./server:/app

    redis:
        image: redis
        hostname: redis
        container_name: redis
        ports:
            - "6379:6379"
        