version: "2.2"

services:
    proxy:
        image: nginx:alpine
        container_name: "{{cookiecutter.project_slug}}-proxy"
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf.d/:/etc/nginx/conf.d

    server:
        build: ./server
        container_name: "{{cookiecutter.project_slug}}-server"
        hostname: "{{cookiecutter.project_slug}}-server"
        volumes:
            - ./server:/app

    redis:
        image: redis
        hostname: "{{cookiecutter.project_slug}}-redis"
        container_name: "{{cookiecutter.project_slug}}-redis"
        ports:
            - "6379:6379"
        