version: "2.2"

services:
    proxy:
        image: nginx:alpine
        container_name: "cookiecutter-proxy"
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf.d/:/etc/nginx/conf.d

    server:
        build: ./server
        container_name: "cookiecutter-server"
        hostname: "cookiecutter-server"
        volumes:
            - ./server:/app

    redis:
        image: redis
        hostname: "cookiecutter-redis"
        container_name: "cookiecutter-redis"
        ports:
            - "6379:6379"
    
    prediction:
        # image: continuumio/miniconda3
        build: ./prediction_engine
        hostname: "cookiecutter-prediction"
        container_name: "cookiecutter-prediction"
        volumes:
            - ./prediction_engine:/home
        