version: "3.8"

services:
    proxy:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf.d/:/etc/nginx/conf.d

    server:
        build: ./server
        volumes:
            - ./server/src:/app
    
    pg:
        image: postgis/postgis
        environment: 
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5433:5432"

    pg:
        image: postgis/postgis
        container_name: pg
        hostname: "pg"
        environment: 
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres


    redis:
        image: redis
        ports:
            - "6379:6379"
    # prediction:
    #     # image: continuumio/miniconda3
    #     build: ./server/tasks
    #     hostname: "cookiecutter-prediction"
    #     container_name: "cookiecutter-prediction"
    #     volumes:
    #         - ./server/tasks:/home

    worker:
        build: ./task_queue
        volumes:
            - ./task_queue:/home
        ports:
            - "6379:6379"
    