version: "3.8"

services:
    proxy:
        image: nginx:alpine
<<<<<<< HEAD
=======
        container_name: "cookiecutter-proxy"
>>>>>>> 42696a7... Prediction task queue.
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf.d/:/etc/nginx/conf.d

    server:
        build: ./server
<<<<<<< HEAD
=======
        container_name: "cookiecutter-server"
        hostname: "cookiecutter-server"
>>>>>>> 42696a7... Prediction task queue.
        volumes:
<<<<<<< HEAD
            - ./server/src:/app
    
    pg:
        image: postgis/postgis
        environment: 
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5433:5432"
=======
            - ./server:/app
    
    pg:
        image: postgis/postgis
        container_name: pg
        hostname: "pg"
        environment: 
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
>>>>>>> b93f45b... Crud work.


    redis:
        image: redis
<<<<<<< HEAD
        ports:
            - "6379:6379"
    
    # prediction:
    #     # image: continuumio/miniconda3
    #     build: ./server/tasks
    #     hostname: "cookiecutter-prediction"
    #     container_name: "cookiecutter-prediction"
    #     volumes:
    #         - ./server/tasks:/home

    worker:
        build: ./task_queue
        volumes:
            - ./task_queue:/home
=======
        hostname: "cookiecutter-redis"
        container_name: "cookiecutter-redis"
        ports:
            - "6379:6379"
    
    prediction:
        # image: continuumio/miniconda3
        build: ./server/tasks
        hostname: "cookiecutter-prediction"
        container_name: "cookiecutter-prediction"
        volumes:
<<<<<<< HEAD
            - ./prediction_engine:/home
        
>>>>>>> 42696a7... Prediction task queue.
=======
            - ./server/tasks:/home
        
>>>>>>> 6c835bc... Add celery worker functionality.
